### ISSUE TITLE
Not compatible with python 3.10 (current stable)

### ISSUE THREAD

**Issue by isopix** [blueOkiris/bgrm#18]
# bgrm
bgrm.sh: line 15: .venv/bin/activate: No such file or directory
bgrm.sh: line 16: python3.9: command not found
bgrm.sh: line 20: deactivate: command not found

 - - 
packgaged & installed using PKGBUILD from AUR:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bgrm-git

**Comment by blueOkiris** [comment]
I'm on it. It says in the README that it supports >= 3.9, so I should be able to just change the script to use "python ...." instead of "python3.9 ...." and expect users to have that dependency (of course on Arch, through pacman, it will already)

It'll be a little while before I get it to the repo and package formats though

**Comment by blueOkiris** [comment]
Nevermind. Just uninstall the bgrm package, delete /opt/bgrm, clear your cache of it, and reinstall (since it downloads from git)

**Comment by blueOkiris** [comment]
There was another issue created with some dependencies that was unrelated, but I've resolved that, so you should be able to install via AUR now (I just did)
